name: todo_as_issue
description: A command-line interface for converting a TODO list into a list of issues on your GitHub / GitLab repository.
version: 1.1.2
homepage: https://github.com/HicaroD/TodoAsIssue

executables:
  todo_as_issue: todo_as_issue

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  http: ^0.13.5
